### ISSUE TITLE
ubuntu 16.04使用脚本无法安装

### ISSUE THREAD

**Issue by nageshuizeii** [BennyThink/ExpressBot#4]
![image](https://user-images.githubusercontent.com/16527235/40218791-455e9398-5aa5-11e8-86be-935d33458924.png)

**Comment by BennyThink** [comment]
看样子是pip的问题。
```bash
pip install requests
```
看看是不是一样的错。

可否贴上详细信息？使用如下命令
```bash
python --version
lsb_release -a
pip -V
```

**Comment by nageshuizeii** [comment]
requests模块正常安装的

**Comment by nageshuizeii** [comment]
![image](https://user-images.githubusercontent.com/16527235/40219315-662a2d42-5aa7-11e8-9a0a-e625f233ce7d.png)

**Comment by BennyThink** [comment]
那这就有点奇怪了，参考下这两篇文章
[pip Import Error:cannot import name main解决方案](https://blog.csdn.net/tintinetmilou/article/details/80091630)
[pip3安装python包报错：ImportError: cannot import name 'main'](https://majing.io/posts/10000014361164)

**Comment by nageshuizeii** [comment]
https://blog.csdn.net/qq_31643159/article/details/80045275 参考这一篇成功
但是仍然无法成功...
![image](https://user-images.githubusercontent.com/16527235/40220495-e80d8922-5aab-11e8-8175-a37b4aaa0611.png)

**Comment by nageshuizeii** [comment]
目标路径请问是哪里？我看是不是和RSSHub这个项目冲突了

**Comment by BennyThink** [comment]
是和`/home/ExpressBot`这个冲突啦。删除就可以啦
```bash
rm -rf /home/ExpressBot
wget -N --no-check-certificate https://raw.githubusercontent.com/BennyThink/ExpressBot/master/install.sh && bash install.sh
```

**Comment by nageshuizeii** [comment]
实在不好意思，再请教您一下，Turing key是什么？搭建bot不是只需要bot token吗？

**Comment by BennyThink** [comment]
😂聊天的，不用留空字符串就可以啦。类似这样：
TURING_KEY=''

**Comment by nageshuizeii** [comment]
![image](https://user-images.githubusercontent.com/16527235/40222630-b7f529fa-5ab2-11e8-9186-a3d75b6291a5.png)
安装成功，但是跑不起来😢

**Comment by BennyThink** [comment]
```
systemctl start expressbot.service
systemctl status expressbot.service
```
出错的话贴`journalctl -u expressbot.service`
😂
