### ISSUE TITLE
请问可否支持docker？

### ISSUE THREAD

**Issue by nageshuizeii** [BennyThink/ExpressBot#5]
docker image的话比您提供的脚本要方便许多，而且个人部署只需要设置环境变量-e bottoken=<>类似即可，还不需要区分各个操作系统的不同～

**Comment by BennyThink** [comment]
好主意，可是我并不会docker😩如果能有个PR之类的……

**Comment by BennyThink** [comment]
现在已经支持啦！
```bash
docker build -t expressbot:v1 .
docker run -d --restart=always -e TOKEN="TOKEN" -e TURING="KEY"  expressbot:v1
```
详情参见 [README](https://github.com/BennyThink/ExpressBot#%E9%83%A8%E7%BD%B2%E6%96%B9%E6%B3%953%E4%BD%BF%E7%94%A8-docker)
