### ISSUE TITLE
快递100接口请求限制问题

### ISSUE THREAD

**Issue by 0312birdzhang** [BennyThink/ExpressBot#7]
可以用ip代理，自己搭一个 [IPProxyPool](https://github.com/qiyeboy/IPProxyPool) ，能用的ip还是挺多的。

**Comment by BennyThink** [comment]
好主意，要是有个PR神马的就更好了……

**Comment by 0312birdzhang** [comment]
ip池怎么用还没想好，需要合理高效还要代码优美 😹

**Comment by BennyThink** [comment]
[Reference](http://docs.python-requests.org/zh_CN/latest/user/advanced.html#proxies)😂😂😂

**Comment by 0312birdzhang** [comment]
看不懂看不懂 (手动再见)
